bss_demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    # index
    # 省略view层，直接在url层返回页面
    path('', TemplateView.as_view(template_name='index.html', extra_context={'current_page': 'index'}), name='index'),
    # user
    path('user/', include('users.urls', namespace='users')),
    # post
    path('post/', include('posts.urls', namespace='posts')),
    # post
    path('review/', include('reviews.urls', namespace='reviews')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# encoding: utf-8
"""
@desc: 帖子路由
"""

from django.urls import path

from . import views
from posts.views import PostDetail, LikePost, AddPost, TopicDetail, StickyPost,DeletePost

app_name = 'posts'


urlpatterns = [
    path('detail/<int:post_id>/', PostDetail.as_view(), name='post-detail'),
    path('like/', LikePost.as_view(), name='like-post'),
    path('add/', AddPost.as_view(), name='add-post'),
    path('delete/<int:post_id>/', DeletePost.as_view(), name='post-delete'),
    # url中使用了as_view()方法后，返回的闭包会根据请求的方式到对应的视图函数中
    # 找以请求方式命名的函数进行执行。
    path('topic/detail/<int:topic_id>/', TopicDetail.as_view(), name='topic-detail'),
    path('sticky/', StickyPost.as_view()),
]

users/urls.py
# encoding: utf-8
"""
@desc: 用户app路由
"""
from django.urls import path

from .views import UserRegister, UserLogin, UserLogout, UserHome, EditUserProfile, UserList

app_name = 'users'


urlpatterns = [
    path('register/', UserRegister.as_view(), name='user-register'),
    path('login/', UserLogin.as_view(), name='user-login'),
    path('logout/', UserLogout.as_view(), name='user-logout'),
    path('home/<int:user_id>/', UserHome.as_view(), name='user-home'),
    path('list/', UserList.as_view(), name='user-list'),
    path('edit/<int:user_id>/', EditUserProfile.as_view(), name='edit-profile'),
]

posts/models.py
import os.path

from django.db import models

from django.conf import settings
from django.urls import reverse


class Topic(models.Model):
    """
    版块
    """
    title = models.CharField(max_length=32, verbose_name='板块名')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='user_topics', verbose_name='版主')
    created = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')

    class Meta:
        verbose_name = '版块'
        verbose_name_plural = verbose_name
        ordering = ('-created',)   # 按照创造日期降序排序板块

    def get_absolute_url(self):
        """
        获取版块绝对路径
        :return:
        """
        # path('topic/detail/<int:topic_id>/', TopicDetail.as_view(), name='topic-detail'),
        # reverse找到视图名 pk是位置参数 *args表示任意多个任意类型无名参数,是一个元组
        return reverse('posts:topic-detail', args=[self.pk])

    def __str__(self):
        return self.title


class Post(models.Model):
    """
    帖子表
    """
    title = models.CharField(max_length=64, verbose_name='标题')  # 必填字段不指定null和blank
    content = models.TextField(verbose_name='内容')
    cover_image = models.ImageField(upload_to='image/post/cover/',
                                    blank=True, null=True, verbose_name='封面图(可选项)')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='user_posts', verbose_name='作者')
    # 一个板块对应多个帖子，一对多的关系，topic_posts
    # 关于related_name的作用 https://blog.csdn.net/wuliangtianzu/article/details/82656647
    # related_name 使用在一对多关系中的 "多" 建立外键时
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE, related_name='topic_posts',
                              null=True, blank=True, verbose_name='所属版块(可选项)')
    src_url = models.CharField(max_length=200, blank=True, null=True, verbose_name='原文链接(可选项)')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True,
                                        related_name='like_posts', verbose_name='点赞的用户')
    like_count = models.PositiveIntegerField(default=0, verbose_name='点赞数')
    view_count = models.PositiveIntegerField(default=0, verbose_name='浏览量')
    is_sticky = models.BooleanField(default=False, verbose_name='是否顶置')
    # 时间根据创建时间自动添加
    created = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')

    def get_absolute_url(self):
        """
        获取帖子绝对路径
        :return:
        """
        return reverse('posts:post-detail', args=[self.pk])

    def get_review_list(self):
        """
        获取帖子评论列表
        :return:
        """
        # post = models.ForeignKey(Post, on_delete=models.CASCADE,
        #  related_name='post_reviews',
        # verbose_name='所属帖子')
        # 相当于post.post_reviews.all() post_reviews是一个related_name,用来查询"一"中的所有"多"
        return self.post_reviews.all()

    def get_review_count(self):
        """
        获取帖子评论数（不包括回复）
        :return:
        """
        return self.post_reviews.count()

    class Meta:
        verbose_name = '帖子'
        verbose_name_plural = verbose_name
        ordering = ('-created',)

    def __str__(self):
        return self.title


class Photo(models.Model):
    """
    照片表
    """
    belong_post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="post_photos",
                                    null=True, blank=True, verbose_name='添加图片')
    pic = models.ImageField(upload_to="image/post/content/",
                            blank=True, null=True, verbose_name='图片')
    absolute_url = models.CharField(max_length=200,verbose_name="图片链接")
    class Meta:
        verbose_name = '图片'
        verbose_name_plural = verbose_name

posts/forms.py
# encoding: utf-8
"""
@desc: 帖子表单
"""

from django import forms

from .models import Post


# 使用Django forms.modelform组件
class PostForm(forms.ModelForm):
    class Meta:  # 这里 model fields widgets 是固定写法
        # https://www.cnblogs.com/open-yang/p/11223192.html
        model = Post  # 这个是已经创建的模型类
        fields = ['cover_image', 'topic', 'src_url', 'title', 'content', ]  # 模型类的属性
        widgets = {
            'cover_image': forms.FileInput(attrs={'class': 'form-control border-0 pl-0'}),
            'topic': forms.Select(attrs={'class': 'form-control bg-light'}),
            'src_url': forms.TextInput(attrs={'class': 'form-control bg-light'}),
            'title': forms.TextInput(attrs={'class': 'form-control bg-light'}),
            'content': forms.Textarea(attrs={'class': 'form-control bg-light'}),
        }

posts/views.py
import setuptools.command.saveopts
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Topic
from .forms import PostForm

from posts.models import Photo


class PostDetail(View):
    """
    帖子详情
    """
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=int(post_id))
        post.view_count += 1
        post.save()
        reviews = post.get_review_list()
        photos = post.post_photos.all()   # 查找帖子所有图片传递给页面
        return render(request, 'posts/detail.html', {
            'post': post,
            'photos': photos,
            'reviews': reviews
        })


class LikePost(LoginRequiredMixin, View):
    """
    点赞帖子
    """
    def post(self, request):
        post_id = request.POST.get('postId', None)
        action = request.POST.get('action', None)
        if request.is_ajax() and post_id and action:
            try:
                post = get_object_or_404(Post, id=int(post_id))
                if action == 'like':
                    post.like_users.add(request.user)
                    post.like_count += 1
                else:
                    post.like_users.remove(request.user)
                    post.like_count -= 1
                post.save()
                return JsonResponse({'msg': 'ok'})
            except BaseException as e:
                print(e)
        return JsonResponse({'msg': 'ko'})


class AddPost(LoginRequiredMixin, View):
    """
    发布帖子
    """
    def get(self, request):
        form = PostForm()
        return render(request, 'posts/add.html', {'form': form})

    def post(self, request):
        form = PostForm(data=request.POST, files=request.FILES)
        files = request.FILES.getlist("post_img_files")
        if form.is_valid():
            try:
                # 以下三行将帖子数据保存到数据库
                # https://blog.csdn.net/qq_21570029/article/details/79728458
                new_post = form.save(commit=False)
                new_post.user = request.user
                new_post.save()

                for file in files:
                    media_url = "/media/image/post/content/" + file.name
                    new_photo = Photo(belong_post=new_post)
                    new_photo.absolute_url = media_url
                    new_photo.pic = file.name
                    new_photo.save()
                    destination = open('/home/ubuntu/mysite/Django/media/image/post/content/' + file.name, 'wb+')
                    for chunk in file.chunks():
                        destination.write(chunk)
                    destination.close()

                # 发帖成功后页面重定向到用户个人主页
                return HttpResponseRedirect(request.user.get_absolute_url())
            except BaseException as e:
                print(e)
        return render(request, 'posts/add.html', {
            'form': form,
            'msg': 'ko'
        })


class DeletePost(View):
    """
    删除帖子
    """
    def post(self, request, post_id):
        post1 = get_object_or_404(Post, id=int(post_id))
        user = post1.user
        post1.delete()
        return HttpResponseRedirect(user.get_absolute_url())

class TopicDetail(View):
    """
    板块详情
    """
    # path('topic/detail/<int:topic_id>/', TopicDetail.as_view(), name='topic-detail'),
    # 在URL中用path方法使用<int>捕获url中的参数传递给视图函数
    # topic_id是url解析器捕获的参数丢给视图函数的
    def get(self, request, topic_id):
        topic = get_object_or_404(Topic, id=int(topic_id)) # 查询语句根据id查找板块名
        # 由于一个板块对应多个帖子属于一对多的关系，故在models.py中使用related_name
        # 在定义主表的外键的时候，给这个外键定义好一个名称
        posts = topic.topic_posts.order_by('-is_sticky')
        current_page = 'Topic'
        return render(request, 'posts/topic-detail.html', {
            'current_page': current_page,
            'topic': topic,
            'posts': posts,  # 将这些参数放在字典中使用render函数传递给模板
            'topic_id': topic.id
        })


class StickyPost(LoginRequiredMixin, View):
    """
    顶置帖子(默认只有管理员可以顶置帖子）
    """
    def post(self, request):
        post_id = request.POST.get('pid', None)
        action = request.POST.get('action', None)

        if request.is_ajax() and post_id and action:
            try:
                post = get_object_or_404(Post, id=int(post_id))
                if action == 'sticky':
                    post.is_sticky = True
                else:
                    post.is_sticky = False
                post.save()
                return JsonResponse({'msg': 'ok'})
            except BaseException as e:
                print(e)
        return JsonResponse({'msg': 'ko'})

templates/posts/add.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
    发布帖子
{% endblock %}


{% block content %}
    <div class="row mb-5">
        <div class="col-md-10 offset-md-1">
            <div class="mt-2">
                <!--必须有enctype=“multipart/form-data”-->
                <form method="POST"
                      enctype="multipart/form-data" action="{% url 'posts:add-post' %}">
                    {% csrf_token %}
                    {{ form.as_p }} <!--通过form对象的as_p方法在前端渲染成p标签的形式-->
                    <p><label for="ClubImagesUpload" id="submit_image">添加图片(可选项):
                        <input type="file" accept="image/*" name="post_img_files"
                               id="ClubImagesUpload" style="display:none" multiple="multiple"/>
                        <img src="https://img1.baidu.com/it/u=2294168426,2339550354&fm=26&fmt=auto&gp=0.jpg"
                             class="addImg mt-2" style="display:block"
                        height="80px" width="80px"/>
                        </label>
                        <div id="preview">

                        </div>
                    </p>
                    <input type="submit" id="submit" name="submit"
                       class="btn btn-outline-success float-right mt-3" value="确认发布">
                </form>

            </div>

        </div>

    </div>
{% endblock %}


{% block js %}
    <script type="text/javascript">
        {% ifequal msg 'ko' %}
            tips('好气啊，提交失败啦', 'danger');
        {% endifequal %}



    </script>
{% endblock %}

templates/posts/detail.html
{% extends 'base.html' %}

{% load post_tags %}

{% block title %}
    帖子详情
{% endblock %}


{% block content %}
    <div class="row mb-5">
        <div class="col-md-10 offset-md-1">
            <div class="post-title">
                <h4>
                    {{ post.title }}
                </h4>
            </div>
            <div class="post-meta mt-3">
                <div class="row">
                    <div class="col-md-10">
                        <div class="media text-muted m-auto">
                            <a href="#">
                                <img src="{{ post.user.avatar.url }}" alt="" class="user-avatar-post mr-2 mt-1 rounded">
                            </a>
                            <div class="media-body small lh-125 ">
                                <div class="m-auto">
                                    <a href="{{ post.user.get_absolute_url }}">
                                        <strong class="card-link">{{ post.user }}</strong>
                                    </a>
                                </div>
                                <span class="card-link">
                                    发布于 {{ post.created }}
                                </span>
                                <span class="card-link">
                                    浏览 {{ post.view_count }}
                                </span>
                                <span class="card-link">
                                    评论 {{ post.get_review_count }}
                                </span>
                                 <span class="card-link">
                                    点赞 <span class="like-count-text">{{ post.like_count }}</span>
                                </span>
                            </div>
                        </div>
                    </div>
                    {% if request.user.is_authenticated %}
                        <div class="col-md-2">
                            <!--自定义标签，后两个为传递参数-->
                        {% check_is_like_post post.id request.user as is_like %}
                            {% if is_like %}
                                <button class="btn btn-sm btn-outline-danger float-right" id="like-post" data-pid="{{ post.id }}" data-action="unlike">
                                    <span class="like-thumbs"><i class="fa fa-thumbs-up" aria-hidden="true"></i></span>
                                    <span class="like-text">已点赞</span>
                                    <span class="like-count">{{ post.like_count }}</span>
                                </button>
                            {% else %}
                                 <button class="btn btn-sm btn-outline-secondary float-right" id="like-post" data-pid="{{ post.id }}" data-action="like">
                                    <span class="like-thumbs"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i></span>
                                    <span class="like-text">点赞</span>
                                    <span class="like-count">{{ post.like_count }}</span>
                                </button>
                            {% endif %}
                        </div>
                    {% endif %}

                </div>
            </div>
            <div class="post-info mt-3">
                <span style="font-size:20px">
                    {{ post.content|linebreaks }}
                </span>
            </div>
            <div class="row">
                {% if photos %}
                    {% for photo in photos %}
                    <div class="col-4 mt-2" style="min-width:240px">
                        <img src="{{ photo.absolute_url }}" width="240px" height="240px" />
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="post-meta mt-3">
                {% if post.topic %}
                    <a href="{{ post.topic.get_absolute_url }}" class="text-red card-link badge badge-light">{{ post.topic }}</a>
                {% endif %}

                {% if post.topic %}
                    <a target="_blank" href="{{ post.src_url }}" class="text-red card-link badge badge-light">原文链接</a>
                {% endif %}


            </div>

            <div class="review-form mt-3">
                <div class="form-group">
                    <label for="review" class="text-muted">
                    </label>
                    <textarea class="form-control bg-light" placeholder="写下你的评论..." rows="3" id="review-text"></textarea>
                </div>


                {% if request.user.is_authenticated %}
                    <div class="mt-2">
                         <button data-pid="{{ post.id }}"
                                 class="btn btn-sm btn-outline-success float-right"
                                 id="btn-review">
                             发表评论
                         </button>
                    </div>
                {% else %}
                    <div class="mt-2">
                         <a role="button" target="_blank" href="{% url 'users:user-login' %}" class="btn btn-sm btn-outline-success float-right">
                             登录后回复
                         </a>
                     </div>
                {% endif %}
            </div>
            <h6 class="border-bottom border-gray pb-2 mt-5">
                <strong>
                    <span class="review-count">
                        {{ post.get_review_count }} 条评论
                    </span>
                </strong>
            </h6>
            <div class="review-list" id="reviews">
                {% include 'reviews/review-list.html' with reviews=reviews %}
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
    <script type="text/javascript">
        $('button#like-post').click(function () {
            var $this = $(this);
            var postId = $this.data('pid');
            var action = $this.data('action');
            var likeCount = parseInt($('span.like-count').text());
            var data = {
                'postId': postId,
                'action': action
            };
            $.ajax({
                cache: false,
                type: 'POST',
                url: '/post/like/',
                data: data,
                async: true,
                success: function (response) {
                    if (response.msg === 'ok'){
                        $this.data('action', action === 'like' ? 'unlike' : 'like');
                        if (action === 'like') {
                            $this.removeClass('btn-outline-secondary');
                            $this.addClass('btn-outline-danger');
                            $('span.like-thumbs').html('<i class="fa fa-thumbs-up" aria-hidden="true"></i>');
                            $('span.like-text').text('已点赞');
                            $('span.like-count').text(likeCount + 1);
                        } else {
                            $this.removeClass('btn-outline-danger');
                            $this.addClass('btn-outline-secondary');
                            $('span.like-thumbs').html('<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>');
                            $('span.like-text').text('点赞');
                            $('span.like-count').text(likeCount - 1);
                        }
                        $('span.like-count-text').text($('span.like-count').text());
                    }
                }
            });
        });
        $('button#btn-review').click(function () {
            var $this = $(this);
            var postId = $this.data('pid');
            var replyText = $.trim($('textarea#review-text').val());

            if (replyText === '') {
                tips('回复内容不能为空~', 'danger');
                return false;
            }

            var data = {
              'postId': postId,
              'text': replyText
            };
            $.ajax({
                cache: false,
                type: 'POST',
                url: '/review/add/review/',
                data: data,
                async: true,
                success: function (response) {
                    if (response.msg === 'ok'){
                        tips('评论成功~', 'success');
                        setTimeout(function () {
                            location.reload();
                        }, 1500);
                        return true;
                    } else {
                        setTimeout(function () {
                            location.reload();
                        }, 1500);
                        tips('评论失败, 请稍后重试', 'danger');
                        return false;
                    }
                }
            });
        });
    </script>
{% endblock %}

templates/posts/host-item.html
{% load static %}

<li href="#" class="list-group-item mt-3 border"
style="box-shadow: 6px 6px 6px 6px rgba(0,0,0,0.23);border-radius: 5px;">
    <div class="post-{{ post.id }}">
        <div class="user-info m-auto text-muted">
            <img class="user-avatar rounded" src="{{ post.user.avatar.url }}" alt="avatar">
            <a href="{{ post.get_absolute_url }}">
                <span class="ml-1 mr-2 mt">{{ post.user }}</span>
            </a>
        </div>
        <div class="post-info">
            <div class="d-flex">
                <div class="post-content text-truncate">
                    <h6 class="mt-2 mb-2 text-truncate">
                        <a href="{{ post.get_absolute_url }}" class="text-dark">
                            <strong>{{ post.title }}</strong>
                        </a>
                    </h6>
                </div>
            </div>
        </div>
       <div class="post-meta mt-1 mb-2 small">
            {% if post.topic %}
                <a href="{{ post.topic.get_absolute_url }}" class="text-red card-link badge badge-light">{{ post.topic }}</a>
            {% endif %}
            <a class="card-link  badge badge-light text-muted">
                <i class="fa fa-eye" aria-hidden="true"></i> {{ post.view_count}}
            </a>
            <a class="card-link badge badge-light text-muted">
                <!--Django模板中{{varible}}包含的变量可以是视图传递给它的字典的key字段-->
                <!--可以是模型中一个实例对象的属性和方法-->
                <i class="fa fa-comment-o" aria-hidden="true"></i> {{ post.get_review_count }}
            </a>
            <a class="card-link badge badge-light text-muted">
                <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> {{ post.like_count }}
            </a>
        </div>
    </div>
</li>

templates/posts/hot-list.html
<div class="list-group list-group-flush">
    <!--posts是通过index.html文件在post_tags.py文件中查询到的4个热门帖子-->
    {% for post in posts %}
        {% include 'posts/host-item.html' with post=post %}
    {% endfor %}
</div>

templates/posts/item-home.html
{% load static %}  <!--可以使用Django模板的static标签-->
<!--用户个人主页显示页面-->
<li class="list-group-item mt-3 border"
style="box-shadow: 4px 4px 6px 2px rgba(0,0,0,0.23);border-radius: 10px;">
    <div class="post-{{ post.id }}">
        <div class="user-info m-auto text-muted">
            <img class="user-avatar-nav rounded" src="{{ post.user.avatar.url }}" alt="avatar">
            <a href="{{ post.user.get_absolute_url }}">
                <span class="ml-1 mr-2 mt">{{ post.user }}</span>
            </a>

            <span class="">{{ post.created }}</span>
            <div class="nav-item dropdown mr-3" style="float:right;">
                <a class="nav-link dropdown-toggle" href=""
                   id="navbarDropdown" role="button" style="color: gray"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-grid-fill" viewBox="0 0 16 16">
                        <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zm8 0A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm-8 8A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm8 0A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3z"/>
                    </svg>
                </a>
                <form id="safe_delete_{{ post.id }}" style="display:none"
                action="{% url 'posts:post-delete' post.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">起~飞</button>
                </form>
                {% ifequal user request.user %}
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item delete_post_{{ post.id }}"
                            href="javascript:void(0)">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-archive-fill" viewBox="0 0 16 16">
                                <path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/>
                            </svg>
                            &nbsp&nbsp删除此贴
                        </a>
                    </div>
                {% endifequal %}
            </div>
        </div>
        <div class="post-info">
            <div class="d-flex">
                <!--text-truncate 文本截断-->
                {% if post.cover_image %}
                <div class="mt-2">
                    <img class="img-responsive rounded" style="height: 209px; width: 314px" src="{{ post.cover_image.url }}" alt="">
                    <div style="position:absolute; margin-left:334px; bottom:73%;">
                        <h5 class="mt-2 mb-2 text-dark">
                        <!--帖子的url-->
                            <a href="{{ post.get_absolute_url }}" class="text-dark">
                                <strong> {{ post.title }}</strong>
                            </a>
                        </h5>
                    </div>
                </div>
                <div class="text-truncate" style="margin-top:6%; margin-left:20px">
                    <span class="text-muted"> {{ post.content }} </span>
                </div>
                {% else %}
                <div class="mt-2">
                    <div>
                        <h5 class="mt-2 mb-2 text-dark">
                        <!--帖子的url-->
                            <a href="{{ post.get_absolute_url }}" class="text-dark">
                                <strong> {{ post.title }}</strong>
                            </a>
                        </h5>
                    </div>
                    <div class="text-truncate">
                        <span class="text-muted"> {{ post.content }} </span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="post-meta mt-1 mb-2">
            {% if post.topic %}
                <a href="{{ post.topic.get_absolute_url }}" class="text-red card-link badge badge-light">{{ post.topic }}</a>
            {% endif %}
            <a class="card-link  badge badge-light text-muted">
                <i class="fa fa-eye" aria-hidden="true"></i> {{ post.view_count }}
            </a>
            <a class="card-link badge badge-light text-muted">
                <i class="fa fa-comment-o" aria-hidden="true"></i> {{ post.get_review_count }}
            </a>
            <a class="card-link badge badge-light text-muted">
                <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> {{ post.like_count }}
            </a>
        </div>
    </div>
</li>
<script>
    $(".delete_post_{{ post.id }}").click(function(){
        layer.open({
            title: "确认删除",
            btn: ["确认", "取消"],
            content: "您确认要删除这篇帖子吗?",
            yes: function(index, layero){
                $("form#safe_delete_{{ post.id }} button").click();
                layer.close(index);
            },
            bt2: function(index, layero) {
                layer.close(index);
            }
        });
    });
</script>

templates/posts/list-home.html
<div class="list-group list-group-flush">
    {% for post in posts %}
        {% include 'posts/item-home.html' with post=post %}
    {% endfor %}
</div>

templates/posts/list.html
<div class="list-group list-group-flush">
    <!---->
    {% for post in posts %}
        {% include 'posts/item.html' with post=post %}
    {% endfor %}
</div>

templates/posts/topic-detail.html
{% extends 'base.html' %}

{% load post_tags %}

{% block title %}
    版块详情
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-9">
            <!--posts是来自视图的参数，之前用过templatetags as别名定义过同样的东西-->
            <!--显示板块内所有帖子-->
            {% include 'posts/list.html' with posts=posts %}
            {% if not posts %}
                <p>暂无帖子</p>
            {% endif %}
        </div>
        <div class="col-md-3">
            <h6 class="border-bottom border-gray pb-2">版主</h6>
            {% include 'users/item.html' with user=topic.user %}

            <h6 class="border-bottom border-gray pb-2 mt-3">热门帖子</h6>
            {% get_hot_posts as hot_posts %}
            {% include 'posts/hot-list.html' with posts=hot_posts %}

        </div>
    </div>
{% endblock %}