bss_demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    # index
    # 省略view层，直接在url层返回页面
    path('', TemplateView.as_view(template_name='index.html', extra_context={'current_page': 'index'}), name='index'),
    # user
    path('user/', include('users.urls', namespace='users')),
    # post
    path('post/', include('posts.urls', namespace='posts')),
    # post
    path('review/', include('reviews.urls', namespace='reviews')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# encoding: utf-8
"""
@desc: 帖子路由
"""

from django.urls import path

from . import views
from posts.views import PostDetail, LikePost, AddPost, TopicDetail, StickyPost,DeletePost

app_name = 'posts'


urlpatterns = [
    path('detail/<int:post_id>/', PostDetail.as_view(), name='post-detail'),
    path('like/', LikePost.as_view(), name='like-post'),
    path('add/', AddPost.as_view(), name='add-post'),
    path('delete/<int:post_id>/', DeletePost.as_view(), name='post-delete'),
    # url中使用了as_view()方法后，返回的闭包会根据请求的方式到对应的视图函数中
    # 找以请求方式命名的函数进行执行。
    path('topic/detail/<int:topic_id>/', TopicDetail.as_view(), name='topic-detail'),
    path('sticky/', StickyPost.as_view()),
]

users/urls.py
# encoding: utf-8
"""
@desc: 用户app路由
"""
from django.urls import path

from .views import UserRegister, UserLogin, UserLogout, UserHome, EditUserProfile, UserList

app_name = 'users'


urlpatterns = [
    path('register/', UserRegister.as_view(), name='user-register'),
    path('login/', UserLogin.as_view(), name='user-login'),
    path('logout/', UserLogout.as_view(), name='user-logout'),
    path('home/<int:user_id>/', UserHome.as_view(), name='user-home'),
    path('list/', UserList.as_view(), name='user-list'),
    path('edit/<int:user_id>/', EditUserProfile.as_view(), name='edit-profile'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<!--加载posts app的templatetags自定义模板标签文件以在模板中使用自定义标签-->
{% load post_tags %}
<html lang="zh-cn">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>{% block title %}{% endblock %}</title>
		<!-- Bootstrap CSS -->
    	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <link href="{% static 'css/font-awesome.min.css' %}" rel='stylesheet'>
        <link href="{% static 'css/animate.min.css' %}" rel='stylesheet'>
    	<link rel="stylesheet" href="{% static 'css/app.css' %}" />
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/layer/layer.js' %}"></script>
        <style>
            {% ifequal 'index' current_page %}
                #b {
                    background:url('https://images4.alphacoders.com/876/876898.jpg') center center no-repeat;
                }
            {% endifequal %}
            {% ifequal 'Topic' current_page %}
                #b {
                    background:url('https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fpic1.win4000.com%2Fwallpaper%2Fd%2F55dae5b338898.jpg&refer=http%3A%2F%2Fpic1.win4000.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1624718800&t=8750f14671aaa70e1dadb9c37df47732') center center no-repeat;
                }
            {% endifequal %}
            {% ifequal 'Home' current_page %}
                #b {
                    background:url('https://images4.alphacoders.com/876/876898.jpg') center center no-repeat;
                }
            {% endifequal %}
            {% ifequal 'register' current_page %}
                #b {
                    height:610px;
                    background:url('https://pages.anjukestatic.com/usersite/site/img/PlugLogin/bg.jpg') center center no-repeat;
                }
            {% endifequal %}
            {% ifequal 'login' current_page %}
                #b {
                    height:610px;
                    background:url('https://pages.anjukestatic.com/usersite/site/img/PlugLogin/bg.jpg') center center no-repeat;
                }
            {% endifequal %}
        </style>
        {% block css %}

        {% endblock %}
	</head>
	<body id="b">
		<nav class="navbar navbar-expand-xl navbar-light bg-white fixed-top border border-left-0 border-right-0 border-top-0 border-gery">

			<div class="container">
                <a class="navbar-brand" href="{% url 'index' %}"> <strong class="text-red">校园论坛</strong> </a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

			  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{% url 'index' %}">
                                <!--ifequal标签比较两个值，当两个相等时显示标签里的内容即text-red-->
                                <span class="{% ifequal 'index' current_page %} text-red {% endifequal %}">
                                     全部
                                </span>
                            </a>
                        </li>

                        <!--获取所有的板块-->
                        {% get_topic_list as topics %}
                        {% for topic in topics %}
                            <li class="nav-item">
                                <a class="nav-link stopic_{{ topic.id }}"
                                   href="{{ topic.get_absolute_url }}">
                                    <!--topic.id是板块的id属性，topic_id是path中捕获的url变量-->
                                    <span class="{% ifequal topic.id topic_id %} text-red {% endifequal %}">
                                         {{ topic }}
                                    </span>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>

                    <form class="form-inline my-2 my-lg-0">
                        <ul class="navbar-nav mr-auto">
                             {% if request.user.is_authenticated %}
{#                                 <li class="nav-item">#}
{#                                  <a class="nav-link {% ifequal 'notice' current_page %}text-red{% endifequal %}" href="#">#}
{#                                      <i class="fa fa-bell-o" aria-hidden="true"></i> 消息#}
{#                                      {% if unread_count %}#}
{#                                          <span class="badge badge-pill badge-danger">{{ unread_count }}</span>#}
{#                                      {% endif %}#}
{#                                  </a>#}
{#                                </li>#}
                              <li class="nav-item dropdown mr-3">
                                  <!--request.user-->
                                  <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      <img class="user-avatar-nav rounded" src="{{ request.user.avatar.url }}" alt="avatar" />
                                  </a>
                                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                      <a class="dropdown-item" href="{{ request.user.get_absolute_url }}"><i class="fa fa-user-o" aria-hidden="true"></i> 个人主页</a>
                                      <a href="javascript:void(0)" class="dropdown-item logout"><i class="fa fa-sign-out" aria-hidden="true"></i> 退出登录</a>
                                </div>
                              </li>
                              <a href="{% url 'posts:add-post' %}"
                                class="send-post btn btn-outline-danger pt-2" target="_blank">
                                <i class="fa fa-pencil" aria-hidden="true"></i> 发帖子
                              </a>
                              {% else %}
                              <li class="nav-item">
                                  <a class="nav-link" href="{% url 'users:user-register' %}">
                                      <span class="{% ifequal 'register' current_page %} text-red {% endifequal %}">
                                          注册
                                      </span>
                                  </a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link" href="{% url 'users:user-login' %}">登录</a>
                              </li>
                             {% endif %}
                        </ul>
                    </form>
			    </div>
			</div>
		</nav>

		<div class="main container" style="margin-top:74px">
            {% block content %}

            {% endblock %}
		</div>


		<!-- Optional JavaScript -->
	    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap-notify.min.js' %}" type="text/javascript"></script>
        <script type="text/javascript">
             $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
             });
             {% if request.user.is_authenticated %}
                $('a.logout').click(function () {
                    $.ajax({
                        cache: false,
                        type: 'GET',
                        url: '/user/logout/',
                        async: true,
                        success: function (response) {
                            if (response.msg === 'ok'){
                                tips('成功退出登录，页面即将刷新~', 'success');
                                setTimeout(function () {
                                    window.location.href = '/';
                                }, 1500);
                                return true;
                            } else {
                                tips('诶呀~，操作失败，请再试一次吧。', 'danger');
                                return false;
                            }
                        }
                    });
                });
            {% endif %}
        </script>
        <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
        {% block js %}

        {% endblock %}
	</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% load post_tags %}
{% load user_tags %}


{% block title %}
    首页
{% endblock %}


<!--父模板base.html中定义的content块，这里在index子模板中对其进行重写（其实是填充），因为父模板里没东西-->
{% block content %}
    <div class="row">
        <div class="col-md-9">
            <!--所有的动态生成网页都是配合django自定义标签templatetags加include with完成的-->
            {% get_all_posts as posts %}
            {% include 'posts/list.html' with posts=posts %}
        </div>
        <div class="col-md-3">
            <h6 class="border-bottom border-gray pb-2">最新加入</h6>
            {% get_online_users as online_users %}
            {% include 'users/list.html' with users=online_users %}
            <small class="d-block text-right mt-2">
                <!--由于使用了路由分发，users指定了在哪个app下-->
                <a href="{% url 'users:user-list' %}" style="color:black">全部用户</a>
            </small>
            <h6 class="border-bottom border-gray pb-2 mt-3">热门帖子</h6>
            {% get_hot_posts as hot_posts %}
            <!--include标签允许在模板中包含其它的模板的内容-->
            <!--如果要在导入变量的时候传递参数，使用with的方法-->
            <!--将host_posts作为posts传递到hot-list.html文件中-->
            {% include 'posts/hot-list.html' with posts=hot_posts %}
        </div>
    </div>
{% endblock %}